# H2 DB -> web console access permit
spring:
  # OAuth
  profiles:
    include: oauth
  datasource:
    ##mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simple_board?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: chma0326@
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
