# H2 DB -> web console access permit
spring:
  # OAuth
  profiles:
    include: oauth
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true